language: cpp

os:
  - osx

branches:
  except:
    - gh-pages

before_install:
  - brew update

install:
  - brew install qt5
  - brew link --force qt5

script:
  # Run qmake and make
  - qmake -config release
  - make
  - ls -alh
  - ls -alh build
  - ls -alh build/release
  # mac specific deployment
  - /usr/local/opt/qt5/bin/macdeployqt build/release/YUView.app -always-overwrite -verbose=2
  # check what YUView is linking against
  - otool -L build/release/YUView.app/Contents/MacOs/YUView
  # copy the libde265 library
  - cp libde265/libde265-internals.dylib build/release/YUView.app/Contents/MacOS/.
  # prepare zip package
  - cd build/release
  - zip -r ../../YUView-MacOs.zip YUView.app
  - cd ../..
  - 'if [ ${TRAVIS_BRANCH} = "master" ]; then ./deployment/deploy_to_github.sh fi'

after_success:
  # not needed?

before_deploy:
  # not needed?
deploy:
  # we could also put the package somewhere else

