name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include: 
          - os: ubuntu-16.04
            QT_FILE: qtBase_5.14.2_xenial.zip
            LIBDE265_REMOTE: libde265.so
            LIBDE265_LOCAL: libde265-internals.so
            ARTIFACT_NAME: YUView.AppImage
            UNZIP_COMMAND: unzip -qa
          - os: windows-2019
            auto_update: true
            QT_FILE: qtBase_5.14.2_win.zip
            QT_DEPLOY: qtTools_5.14.2_win.zip
            LIBDE265_REMOTE: libde265.dll
            LIBDE265_LOCAL: libde265.dll
            ARTIFACT_NAME: YUView-Win.zip
            UNZIP_COMMAND: 7z x
          - os: windows-2019
            auto_update: false
            QT_FILE: qtBase_5.14.2_win.zip
            QT_DEPLOY: qtTools_5.14.2_win.zip
            LIBDE265_REMOTE: libde265.dll
            LIBDE265_LOCAL: libde265.dll
            ARTIFACT_NAME: YUView-Win-noautoupdate.zip
            UNZIP_COMMAND: 7z x
          - os: macos-10.15
            QT_FILE: qtBase_5.14.2_mac.zip
            QT_DEPLOY: qtTools_5.14.2_mac.zip
            LIBDE265_REMOTE: libde265.dylib
            LIBDE265_LOCAL: libde265-internals.dylib
            ARTIFACT_NAME: YUView-Mac.zip
            UNZIP_COMMAND: unzip -qa
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: Install Qt base
      run: |
        cd ../../
        mkdir -p YUViewQt/YUViewQt
        cd YUViewQt/YUViewQt
        curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtBase-5.14.2/${{matrix.QT_FILE}} -o Qt.zip
        ${{matrix.UNZIP_COMMAND}} Qt.zip
        echo "::add-path::$GITHUB_WORKSPACE/../../YUViewQt/YUViewQt/Qt/bin"
      shell: bash
    - name: Install Qt deploy tools
      run: |
        cd $GITHUB_WORKSPACE/../../YUViewQt/YUViewQt
        curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtDeployTools-5.14.2/${{matrix.QT_DEPLOY}} -o deployQt.zip
        ${{matrix.UNZIP_COMMAND}} deployQt.zip
      shell: bash
      if: matrix.os == 'macos-10.15' || matrix.os == 'windows-2019'
    - name: Install Macdeploy Qt
      run: |
        cp $GITHUB_WORKSPACE/../../YUViewQt/YUViewQt/Qttools/bin/macdeployqt $GITHUB_WORKSPACE/../../YUViewQt/YUViewQt/Qt/bin/macdeployqt
        strip $GITHUB_WORKSPACE/../../YUViewQt/YUViewQt/Qt/bin/macdeployqt
      if: matrix.os == 'macos-10.15'
    - name: Install Linuxdeployqt
      run: |
        curl -L https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -o linuxdeployqt-6-x86_64.AppImage
        chmod a+x linuxdeployqt-6-x86_64.AppImage
      if: matrix.os == 'ubuntu-16.04'
    - name: Install Linux packages
      run: |
        sudo apt install libgl1-mesa-dev libxkbcommon-x11-0
      if: matrix.os == 'ubuntu-16.04'
    - name: Install libde265
      run: |
        curl -L https://github.com/ChristianFeldmann/libde265/releases/download/v1.1/${{matrix.LIBDE265_REMOTE}} -o ${{matrix.LIBDE265_LOCAL}}
        curl -L https://raw.githubusercontent.com/ChristianFeldmann/libde265/master/COPYING -o libde265License.txt
      shell: bash
    - name: Install jom (Windows only)
      run: |
        cd $GITHUB_WORKSPACE
        curl -L http://download.qt.io/official_releases/jom/jom.zip -o jom.zip
        7z x jom.zip -ojom
        cp jom/jom.exe $GITHUB_WORKSPACE/../../YUViewQt/YUViewQt/Qt/bin/
      shell: bash
      if: matrix.os == 'windows-2019'
    - name: Install openSSL
      run: |
        mkdir openSSL
        cd openSSL
        curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/openSSL1.1.1g/openSSL_1_1_1g_win.zip -o openSSL.zip
        ${{matrix.UNZIP_COMMAND}} openSSL.zip
        cd ..
      if: matrix.os == 'windows-2019'
      shell: bash
    - name: Build Linux/Mac
      run: |
        cd $GITHUB_WORKSPACE
        export PATH=$GITHUB_WORKSPACE/../../YUViewQt/YUViewQt/Qt/bin:$PATH
        mkdir build
        cd build
        qmake ..
        make -j 2
        make check
      if: matrix.os == 'ubuntu-16.04' || matrix.os == 'macos-10.15'
    - name: Activate auto update (Windows)
      run: sed -i -- "s/#define UPDATE_FEATURE_ENABLE 0/#define UPDATE_FEATURE_ENABLE 1/g" YUViewLib/src/common/typedef.h
      shell: bash
      if: matrix.os == 'windows-2019' && matrix.auto_update == true
    - name: Build Windows
      run: |
        mkdir build
        cd build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        d:\a\YUViewQt\YUViewQt\Qt\bin\qmake ..
        jom
        nmake check
        cd ..
      shell: cmd
      if: matrix.os == 'windows-2019'
    - name: Build App (Mac)
      run: |
        macdeployqt build/YUViewApp/YUView.app -always-overwrite -verbose=2
        cp ${{matrix.LIBDE265_LOCAL}} build/YUViewApp/YUView.app/Contents/MacOS/.
        cd build/YUViewApp
        # Zip
        zip -r ${{matrix.ARTIFACT_NAME}} YUView.app/
        cp ${{matrix.ARTIFACT_NAME}} $GITHUB_WORKSPACE/artifacts
      if: matrix.os == 'macos-10.15'
    - name: Build Appimage (Linux)
      run: |
        cd build
        make INSTALL_ROOT=appdir install
        $GITHUB_WORKSPACE/linuxdeployqt-6-x86_64.AppImage YUViewApp/appdir/usr/local/share/applications/de.rwth_aachen.ient.YUView.desktop -appimage -bundle-non-qt-libs -verbose=2
        mv YUView-*.AppImage YUView.AppImage
        cp YUView.AppImage $GITHUB_WORKSPACE/artifacts
      if: matrix.os == 'ubuntu-16.04'
    - name: Deploy Windows
      run: |
        mkdir deploy
        cd deploy
        cp ../build/YUViewApp/YUView.exe .
        d:\a\YUViewQt\YUViewQt\Qttools\bin\windeployqt.exe --release --dir d:\a\YUView\YUView\deploy --no-compiler-runtime YUView.exe
        cp ../openSSL/*.dll .
        mkdir decoder
        cp ..\libde265.dll decoder
        cp ..\libde265License.txt decoder
        cp ../LICENSE.GPL3 .
        cd ..
        python deployment/versioning.py -d deploy -o deploy/versioninfo.txt
        mkdir artifacts
        7z a artifacts/YUView-Win.zip ./deploy/*
      shell: cmd
      if: matrix.os == 'windows-2019'
    - name: Wix Windows
      run: |
        cd $GITHUB_WORKSPACE/deployment/wix
        cp /c/Program\ Files\ \(x86\)/Common\ Files/Merge\ Modules/Microsoft_VC140_CRT_x64.msm .
        "${WIX}\bin\heat.exe" dir ../../deploy -gg -dr APPLICATIONFOLDER -srd -sreg -cg YUViewComponents -out harvestedDirectory.wxs
        "${WIX}\bin\candle.exe" -dConfiguration=Release -dOutDir=bin/Release/ -dTargetExt=.msi -dTargetFileName=YUViewSetup.msi -dTargetName=YUViewSetup -out obj/Release/ -arch x64 -ext "${WIX}\bin\WixUIExtension.dll" YUView.wxs
        "${WIX}\bin\candle.exe" -dConfiguration=Release -dOutDir=bin/Release/ -dTargetExt=.msi -dTargetFileName=YUViewSetup.msi -dTargetName=YUViewSetup -out obj/Release/ -arch x64 harvestedDirectory.wxs
        "${WIX}\bin\Light.exe" -b ../../deploy -out bin/Release/YUViewSetup.msi -pdbout bin/Release/YUViewSetup.wixpdb -cultures:null -ext "${WIX}\bin\WixUIExtension.dll" -contentsfile obj/Release/YUViewSetup.wixproj.BindContentsFileListnull.txt -outputsfile obj/Release/YUViewSetup.wixproj.BindOutputsFileListnull.txt -builtoutputsfile obj/Release/YUViewSetup.wixproj.BindBuiltOutputsFileListnull.txt obj/Release/YUView.wixobj obj/Release/harvestedDirectory.wixobj
        cd $GITHUB_WORKSPACE
        cp deployment/wix/bin/Release/YUViewSetup.msi ./artifacts
      shell: bash
      if: matrix.os == 'windows-2019' && matrix.auto_update == true
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.ARTIFACT_NAME}}
        path: artifacts

  # How to upload files to the release:
  # https://github.com/Blacksmoke16/oq/pull/47/files#diff-082c28d748ad2e3eecc5508d740d9417R9-R29